apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
          - name: CE_BIN_PORT
            value: "80"
          - name: CE_BIN_REDIS_URL
            value: {{ .Values.redisURL }}
          {{if .Values.redisPasswordSecret}}
          - name: CE_BIN_REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: {{ .Values.redisPasswordSecret }}
                key: redis-password
          {{ end }}
        resources:
{{ toYaml .Values.resources | indent 12 }}
