apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ing-{{ template "fullname" . }}
  annotations:
    {{- if .Values.ingressClass }}
    kubernetes.io/ingress.class: {{ .Values.ingressClass }}
    {{- end }}
spec:
  {{- if .Values.tlsSecret }}
  tls:
    - secretName: {{ .Values.tlsSecret }}
  {{- end }}
  backend:
    serviceName: svc-{{ template "fullname" . }}
    servicePort: 80
