apiVersion: v1
kind: Service
metadata:
  name: svc-{{ template "fullname" . }}
spec:
  type: NodePort
  selector:
    app: {{ template "fullname" . }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      name: http
